import mongoose from 'mongoose';

const ItemSchema = new mongoose.Schema({
  itemSNo: { type: Number },
  // Per-row buyer / document details (DSI form stores these per row)
  buyerNTN: { type: String, default: '' },
  buyerCNIC: { type: String, default: '' },
  buyerBusinessName: { type: String, default: '' },
  buyerType: { type: String, default: '' },
  buyerProvince: { type: String, default: '' },
  sellerProvince: { type: String, default: '' },
  invoiceType: { type: String, default: '' },
  invoiceNumber: { type: String, default: '' },
  invoiceDate: { type: String, default: '' },
  buyerAddress: { type: String, default: '' },
  // Product / value details
  itemDescription: { type: String, default: '', trim: true },
  hsCode: { type: String, default: '', trim: true },
  quantity: { type: Number, default: 0 },
  unitPrice: { type: Number, default: 0 },
  saleValue: { type: Number, default: 0 },
  taxRate: { type: Number, default: 0 },
  taxAmount: { type: Number, default: 0 },
  uom: { type: String, default: '' },
  saleType: { type: String, default: '' },
  fixedNotifiedValue: { type: Number, default: 0 },
  extraTax: { type: Number, default: 0 },
  furtherTax: { type: Number, default: 0 },
  fedPayable: { type: Number, default: 0 },
  discount: { type: Number, default: 0 },
  totalValueOfSales: { type: Number, default: 0 },
  stWithheldAtSource: { type: Number, default: 0 },
  invoiceReferenceNo: { type: String, default: '' },
  reasons: { type: String, default: '' },
  reasonRemarks: { type: String, default: '' },
  petroleumLevyOn: { type: String, default: '' },
  sroScheduleNo: { type: String, default: '' },
  sroItemSerialNo: { type: String, default: '' },
});

const SubmissionSchema = new mongoose.Schema(
  {
    companyId: { type: mongoose.Schema.Types.ObjectId, ref: 'Company', required: true },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    submissionType: { type: String, default: 'sale_tax_fed' },
    taxPeriodMonth: { type: Number, required: true },
    taxPeriodYear: { type: Number, required: true },
    invoiceType: { type: String, default: '' },
    invoiceDate: { type: String, default: '' },
    invoiceNumber: { type: String, default: '' },
    sellerBusinessName: { type: String, default: '' },
    sellerNTN: { type: String, default: '' },
    sellerProvince: { type: String, default: '' },
    sellerAddress: { type: String, default: '' },
    buyerBusinessName: { type: String, default: '' },
    buyerNTN: { type: String, default: '' },
    buyerCNIC: { type: String, default: '' },
    buyerProvince: { type: String, default: '' },
    buyerAddress: { type: String, default: '' },
    buyerType: { type: String, default: '' },
    scenarioId: { type: String, default: '' },
    totalSaleValue: { type: Number, default: 0 },
    totalTaxAmount: { type: Number, default: 0 },
    totalBillAmount: { type: Number, default: 0 },
    itemList: [ItemSchema],
    status: {
      type: String,
      enum: ['draft', 'validated', 'ready_for_submission', 'submitted', 'failed'],
      default: 'draft',
    },
    validationStatus: {
      type: String,
      enum: ['pending', 'valid', 'invalid'],
      default: 'pending',
    },
    validationErrors: [{ type: String }],
    fbrPayload: { type: mongoose.Schema.Types.Mixed, default: null },
    fbrResponse: { type: mongoose.Schema.Types.Mixed, default: null },
    submittedAt: { type: Date, default: null },
  },
  { timestamps: true }
);

export default mongoose.models.Submission || mongoose.model('Submission', SubmissionSchema);
